apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "managed-csi-nfs"
  resources:
    requests:
      storage: 50Gi
